---
title: "randomEffectsANOVA"
author: "Natalie"
date: "2024-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(here)
library(nlme)
library(dplyr)
library(VCA)
```

Import classification accuracy dataset
```{r import classification accuracies}
#import a dataset containing all classification accuracies for each subplot and training set 
class_acc <- read.csv(here("Data", "class_acc.csv"))
str(class_acc) #summary of the classification accuracy dataset
```

```{r RE ANOVA}
#conduct the random effects ANOVA test 
re_ANOVA <- lme(Classif_Acc ~ 1, random = ~ 1 | Plot_ID/Subplot_ID, data = class_acc)
re_ANOVA #display results 
```

```{r variance components}
#Obtain the variance components: within a site, between sites and unexplained 
anova_varcomp <- VarCorr(re_ANOVA)
anova_varcomp
```

```{r best train ID}
#Obtain the mean classification accuracy of each training set to see if any one set has a high enough accuracy. 
mean_acc <- class_acc %>%
  group_by(Training_ID) %>%
  summarize(mean_acc = mean(Classif_Acc, na.rm=T)) 
print(mean_acc)
```

```{r graph}
#Plot a graph showing the classification accuracies of each subplot, within each training set
varPlot(form = Classif_Acc ~ Plot_ID/Subplot_ID, Data = class_acc, YLabel = list(text = "Classification Accuracy"))
```

