---
title: "Preprocessing"
author: "Natalie"
date: "2024-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load package}
library(terra)
library(sf)
```

# Remove band 4 in the rasters of all sites
## Band was removed as it was redundant and did not contain any information
```{r Site 1}
#import the site raster
AntelopeBrushBurn <- rast("/home/natw03/Documents/Sites_Reprojected/AntelopeBrushBurn_Reprojected.tif")
#show information about the raster to check
print(AntelopeBrushBurn)
summary(AntelopeBrushBurn)
plot(AntelopeBrushBurn)

#Remove band 4
## Obtain the names of the layers within the raster
lyr_names1 <- names(AntelopeBrushBurn)
## Choose which bands/layers to keep. Since we are removing band 4, we will keep bands 1, 2 and 3.
bands_to_keep1 <- which(lyr_names1 %in% c("AntelopeBrushBurn_Reprojected_1", 
                                        "AntelopeBrushBurn_Reprojected_2", 
                                        "AntelopeBrushBurn_Reprojected_3"))
##Create a new raster "site1" containing only bands 1, 2 and 3 and plot it to ensure necessary bands were not accidentally removed.
site1 <- AntelopeBrushBurn[[bands_to_keep1]]
plot(site1)

#Export new raster 
output_site1 <- "/home/natw03/Documents/Bands_Adjusted/site1.tif"
writeRaster(site1, output_site1)
```

```{r Site 2}
# Import the site raster 
AntelopeBrushFlat <- rast("/home/natw03/Documents/Sites_Reprojected/AntelopeBrushFlat_Reprojected.tif")
# Show information about the raster to check
print(AntelopeBrushFlat)
summary(AntelopeBrushFlat)
plot(AntelopeBrushFlat)

#Remove band 4
## Obtain the names of the layers within the raster
lyr_names2 <- names(AntelopeBrushFlat)
bands_to_keep2 <- which(lyr_names2 %in% c("AntelopeBrushFlat_Reprojected_1",
                                          "AntelopeBrushFlat_Reprojected_2",
                                          "AntelopeBrushFlat_Reprojected_3"))
## Choose which bands/layers to keep. Since we are removing band 4, we will keep bands 1, 2 and 3.
site2 <- AntelopeBrushFlat[[bands_to_keep2]]
plot(site2)

#Export new raster 
output_site2 <- "/home/natw03/Documents/Bands_Adjusted/site2.tif"
writeRaster(site2, output_site2)
```

```{r Site 3}
# Import the site raster
AntelopeBrushFortis <- rast("/home/natw03/Documents/Sites_Reprojected/AntelopeBrushFortis_Reprojected.tif")
# Show information about the raster to check
print(AntelopeBrushFortis)
summary(AntelopeBrushFortis)
plot(AntelopeBrushFortis)

#Remove band 4
## Obtain the names of the layers within the raster
lyr_names3 <- names(AntelopeBrushFortis)
bands_to_keep3 <- which(lyr_names3 %in% c("AntelopeBrushFortis_Reprojected_1",
                                          "AntelopeBrushFortis_Reprojected_2",
                                          "AntelopeBrushFortis_Reprojected_3"))
## Choose which bands/layers to keep. Since we are removing band 4, we will keep bands 1, 2 and 3.
site3 <- AntelopeBrushFortis[[bands_to_keep3]]
plot(site3)

#Export new raster 
output_site3 <- "/home/natw03/Documents/Bands_Adjusted/site3.tif"
writeRaster(site3, output_site3)
```

```{r Site 4} 
# Import the site raster
CommercialRd <- rast("/home/natw03/Documents/Sites_Reprojected/CommercialRd_Reprojected.tif")
# Show information about the raster to check
print(CommercialRd)
summary(CommercialRd)
plot(CommercialRd)

#Remove band 4
## Obtain the names of the layers within the raster
lyr_names4 <- names(CommercialRd)
bands_to_keep4 <- which(lyr_names4 %in% c("CommercialRd_Reprojected_1",
                                          "CommercialRd_Reprojected_2",
                                          "CommercialRd_Reprojected_3"))
## Choose which bands/layers to keep. Since we are removing band 4, we will keep bands 1, 2 and 3.
site4 <- CommercialRd[[bands_to_keep4]]
plot(site4)

#Export new raster 
output_site4 <- "/home/natw03/Documents/Bands_Adjusted/site4.tif"
writeRaster(site4, output_site4)
```

```{r Site 5}
# Import the site raster
FieldsLease <- rast("/home/natw03/Documents/Sites_Reprojected/FieldsLease_Reprojected.tif")
# Show information about the raster to check
print(FieldsLease)
summary(FieldsLease)
plot(FieldsLease)

#Remove band 4
## Obtain the names of the layers within the raster
lyr_names5 <- names(FieldsLease)
bands_to_keep5 <- which(lyr_names5 %in% c("FieldsLease_Reprojected_1",
                                          "FieldsLease_Reprojected_2",
                                          "FieldsLease_Reprojected_3"))
## Choose which bands/layers to keep. Since we are removing band 4, we will keep bands 1, 2 and 3.
site5 <- FieldsLease[[bands_to_keep5]]
plot(site5)

#Export new raster 
output_site5 <- "/home/natw03/Documents/Bands_Adjusted/site5.tif"
writeRaster(site5, output_site5)
```

```{r Site 6}
#Import raster
HaynesLease <- rast("/home/natw03/Documents/Sites_Reprojected/HaynesLease_Reprojected.tif")
# Show information about the raster to check
print(HaynesLease)
summary(HaynesLease)
plot(HaynesLease)

#Remove band 4
## Obtain the names of the layers within the raster
lyr_names6 <- names(HaynesLease)
bands_to_keep6 <- which(lyr_names6 %in% c("HaynesLease_Reprojected_1",
                                          "HaynesLease_Reprojected_2",
                                          "HaynesLease_Reprojected_3"))
## Choose which bands/layers to keep. Since we are removing band 4, we will keep bands 1, 2 and 3.
site6 <- HaynesLease[[bands_to_keep6]]
plot(site6)

#Export new raster 
output_site6 <- "/home/natw03/Documents/Bands_Adjusted/site6.tif"
writeRaster(site6, output_site6)
```

```{r Site 7}
#Import raster
SportmansBowl <- rast("/home/natw03/Documents/Sites_Reprojected/SportmansBowl_Reprojected.tif")
print(SportmansBowl)
summary(SportmansBowl)
plot(SportmansBowl)

#Remove band 4
lyr_names7 <- names(SportmansBowl)
bands_to_keep7 <- which(lyr_names7 %in% c("SportmansBowl_Reprojected_1",
                                          "SportmansBowl_Reprojected_2",
                                          "SportmansBowl_Reprojected_3"))
site7 <- SportmansBowl[[bands_to_keep7]]
plot(site7)

#Export new raster 
output_site7 <- "/home/natw03/Documents/Bands_Adjusted/site7.tif"
writeRaster(site7, output_site7)
```

# Make sure all sites only have 3 bands
```{r}
#Import new rasters
folderPath <- "/home/natw03/Documents/Bands_Adjusted"
raster_files <- list.files(path = folderPath, pattern = "\\.tif$", full.names = TRUE)

#Check if a rasters have 3 bands
check_raster_bands <- function(raster_path) {
  r <- rast(raster_path)
  return(nlyr(r) == 3)
}
#Apply the check to all files in the "raster_files" file path
all_rasters_ok <- all(sapply(raster_files, check_raster_bands))

#If all rasters have 3 bands, display "ok"
if (all_rasters_ok) {
  print("ok")
}else {
  print("not all rasters have 3 bands")}
```

